import { env } from "@/env";

/**
 * Central SEO configuration.
 *
 * Everything that describes the site to crawlers and social scrapers lives here
 * so titles, descriptions, canonical URLs, the sitemap and robots.txt all stay
 * in sync. Page-level metadata is keyed by the Next.js route pattern (the value
 * of `router.pathname`, e.g. "/governance/drep/[id]") and merged with sensible
 * defaults by {@link getRouteSeo}.
 */

/** Canonical origin of the deployment, without a trailing slash. */
export const SITE_URL = (
  env.NEXT_PUBLIC_SITE_URL ?? "https://multisig.meshjs.dev"
).replace(/\/+$/, "");

export const SITE_NAME = "Mesh Multisig";
export const TWITTER_HANDLE = "@meshsdk";

export const DEFAULT_TITLE =
  "Mesh Multisig — Cardano Treasury & Governance Wallet";
export const DEFAULT_DESCRIPTION =
  "Mesh Multisig is a free, open-source, Cardano-native multi-signature wallet. Secure your team or DAO treasury with M-of-N approvals and vote on Cardano governance together.";
export const DEFAULT_KEYWORDS =
  "cardano multisig, multi-signature wallet, cardano treasury, dao treasury, cardano governance, drep, cardano wallet, meshjs, ada, blockchain";

/** Branded 1200×630 social card served from /public (generated by scripts/generate-og-image.mjs). */
export const OG_IMAGE_PATH = "/og-image.png";
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/** Build an absolute URL for a site-relative path. */
export function absoluteUrl(path = "/"): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

export type RouteSeo = {
  /** Page-specific lead used to compose the <title>. Omit on "/" (uses DEFAULT_TITLE). */
  title?: string;
  description?: string;
  keywords?: string;
  noindex?: boolean;
};

/**
 * Per-route metadata keyed by Next.js route pattern. Anything not listed falls
 * back to the site defaults (and is no-indexed if it lives under a private
 * prefix — see {@link NOINDEX_PREFIXES}).
 */
export const routeSeo: Record<string, RouteSeo> = {
  "/": {
    description: DEFAULT_DESCRIPTION,
  },
  "/features": {
    title: "Features",
    description:
      "Multi-signature security, signer invites and verification, full transaction history, governance voting, DRep registration, staking and a REST API — everything Mesh Multisig offers Cardano teams.",
  },
  "/governance": {
    title: "Cardano Governance",
    description:
      "Browse Cardano governance proposals and vote as a team with multi-signature security. Register your organization as a DRep and take part in on-chain decisions.",
  },
  "/governance/drep": {
    title: "DRep Explorer",
    description:
      "Explore Cardano Delegated Representatives (DReps): voting records, delegated stake and metadata. Find a DRep to delegate your Cardano voting power to.",
  },
  "/governance/drep/[id]": {
    title: "DRep Details",
    description:
      "View a Cardano DRep's voting history, delegated stake and on-chain metadata on Mesh Multisig.",
  },
  "/api-docs": {
    title: "API & Bot Documentation",
    description:
      "Interactive OpenAPI / Swagger documentation for the Mesh Multisig REST API. Authenticate bots, query wallets and pending transactions, and build Cardano integrations.",
  },
  "/dapps": {
    title: "DApps",
    description:
      "Use Mesh Multisig with your favourite Cardano DApps in multi-signature mode.",
  },
  "/blog": {
    title: "Blog",
    description:
      "Guides and updates on Cardano multisig treasuries, governance and AI-agent automation from the team behind Mesh Multisig.",
  },
  "/blog/[slug]": {
    // Per-post title/description/Article JSON-LD are supplied at request time via
    // `pageProps.seo` (see buildPostSeo); these are only the fallback.
    title: "Blog",
    description:
      "Guides and updates on Cardano multisig treasuries, governance and AI-agent automation from the team behind Mesh Multisig.",
  },
  "/wallets/import-wallet": {
    title: "Import a Multisig Wallet",
    description:
      "Import an existing Cardano multi-signature wallet into Mesh Multisig and continue collaborating with your signers.",
  },
  "/user": {
    title: "Your Profile",
    noindex: true,
  },
};

/**
 * Route prefixes (by pathname pattern) that should never be indexed: private
 * wallet workspaces, personal invite/creation flows and the profile page.
 */
export const NOINDEX_PREFIXES = [
  "/wallets/[wallet]",
  "/wallets/invite",
  "/wallets/new-wallet",
  "/user",
];

export type ResolvedSeo = {
  title: string;
  description: string;
  keywords: string;
  noindex: boolean;
};

function composeTitle(pathname: string, lead?: string): string {
  if (pathname === "/" || !lead) return DEFAULT_TITLE;
  return `${lead} · ${SITE_NAME}`;
}

/** Resolve the metadata for a Next.js route pattern, merged with site defaults. */
export function getRouteSeo(pathname: string): ResolvedSeo {
  const entry = routeSeo[pathname];
  const noindex =
    entry?.noindex ?? NOINDEX_PREFIXES.some((p) => pathname.startsWith(p));
  return {
    title: composeTitle(pathname, entry?.title),
    description: entry?.description ?? DEFAULT_DESCRIPTION,
    keywords: entry?.keywords ?? DEFAULT_KEYWORDS,
    noindex,
  };
}

export type SitemapRoute = {
  path: string;
  changefreq: "daily" | "weekly" | "monthly";
  priority: number;
};

/** Static, indexable routes emitted into /sitemap.xml. */
export const INDEXABLE_ROUTES: SitemapRoute[] = [
  { path: "/", changefreq: "weekly", priority: 1.0 },
  { path: "/features", changefreq: "monthly", priority: 0.8 },
  { path: "/blog", changefreq: "weekly", priority: 0.7 },
  { path: "/governance", changefreq: "daily", priority: 0.8 },
  { path: "/governance/drep", changefreq: "daily", priority: 0.7 },
  { path: "/api-docs", changefreq: "monthly", priority: 0.6 },
  { path: "/wallets/import-wallet", changefreq: "monthly", priority: 0.5 },
];

/**
 * JSON-LD structured data for the current page. Organization + WebSite appear on
 * every page; the SoftwareApplication entity is added on the home page only.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function buildJsonLd(pathname: string): Record<string, any>[] {
  const organization = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: SITE_NAME,
    url: SITE_URL,
    logo: absoluteUrl("/favicon/apple-touch-icon.png"),
    sameAs: [
      "https://github.com/MeshJS/multisig",
      "https://x.com/meshsdk",
      "https://discord.gg/dH48jH3BKa",
      "https://meshjs.dev",
    ],
  };

  const website = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE_NAME,
    url: SITE_URL,
    description: DEFAULT_DESCRIPTION,
    inLanguage: "en",
  };

  if (pathname !== "/") return [organization, website];

  const application = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: SITE_NAME,
    applicationCategory: "FinanceApplication",
    operatingSystem: "Web",
    url: SITE_URL,
    description: DEFAULT_DESCRIPTION,
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    isAccessibleForFree: true,
    license: "https://www.apache.org/licenses/LICENSE-2.0",
  };

  return [organization, website, application];
}

/**
 * A fully-resolved SEO override a page can return from its data fetcher as
 * `pageProps.seo`. `_app.tsx` renders it through {@link Metatags} *outside* the
 * `ssr:false` boundary, so dynamic pages (e.g. blog posts) get a server-rendered
 * `<head>` with per-page title, description, OG image and JSON-LD.
 */
export type PageSeo = {
  title: string;
  description: string;
  keywords?: string;
  /** Site-relative OG image path. */
  image?: string;
  /** Open Graph object type, e.g. "article". */
  type?: string;
  noindex?: boolean;
  /** Extra JSON-LD blocks appended to the site-wide ones (e.g. Article). */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  jsonLd?: Record<string, any>[];
};

/** Front-matter metadata for a blog post, shared between the data layer and pages. */
export type ArticleMeta = {
  slug: string;
  title: string;
  description: string;
  /** ISO date (YYYY-MM-DD) the post was published. */
  date: string;
  /** ISO date the post was last updated; defaults to `date`. */
  updated?: string;
  tags?: string[];
  /** Site-relative social image; defaults to the site OG image. */
  image?: string;
  author?: string;
};

/** Default byline for blog posts. */
export const BLOG_AUTHOR = "Mesh";

/** schema.org/Article structured data for a single post. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function buildArticleJsonLd(meta: ArticleMeta): Record<string, any> {
  const url = absoluteUrl(`/blog/${meta.slug}`);
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: meta.title,
    description: meta.description,
    image: absoluteUrl(meta.image ?? OG_IMAGE_PATH),
    datePublished: meta.date,
    dateModified: meta.updated ?? meta.date,
    author: {
      "@type": "Organization",
      name: meta.author ?? BLOG_AUTHOR,
      url: SITE_URL,
    },
    publisher: {
      "@type": "Organization",
      name: SITE_NAME,
      logo: {
        "@type": "ImageObject",
        url: absoluteUrl("/favicon/apple-touch-icon.png"),
      },
    },
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    ...(meta.tags?.length ? { keywords: meta.tags.join(", ") } : {}),
  };
}

/** Build the resolved {@link PageSeo} override for a blog post. */
export function buildPostSeo(meta: ArticleMeta): PageSeo {
  return {
    title: `${meta.title} · ${SITE_NAME}`,
    description: meta.description,
    keywords: meta.tags?.length ? meta.tags.join(", ") : DEFAULT_KEYWORDS,
    image: meta.image ?? OG_IMAGE_PATH,
    type: "article",
    noindex: false,
    jsonLd: [buildArticleJsonLd(meta)],
  };
}
