import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import tseslint from "@typescript-eslint/eslint-plugin";
import typescriptParser from "@typescript-eslint/parser";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const typedFiles = ["**/*.{ts,tsx,mts,cts}"];

/**
 * @param {unknown} configs
 * @returns {any[]}
 */
function scopeConfigsToTypedFiles(configs) {
  if (!Array.isArray(configs)) return [];
  return configs.map((config) => (config.files ? config : { ...config, files: typedFiles }));
}

export default [
  {
    // Generated by tests; not part of the source tree we want to lint.
    ignores: ["coverage/**"],
  },
  ...nextCoreWebVitals,
  ...scopeConfigsToTypedFiles(tseslint.configs["flat/recommended-type-checked"]),
  ...scopeConfigsToTypedFiles(tseslint.configs["flat/stylistic-type-checked"]),
  {
    files: typedFiles,
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        // Enable type-aware lint rules.
        project: true,
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        {
          prefer: "type-imports",
          fixStyle: "inline-type-imports",
        },
      ],
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/no-misused-promises": [
        "warn",
        {
          checksVoidReturn: {
            attributes: false,
          },
        },
      ],
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/prefer-for-of": "warn",
      "@typescript-eslint/non-nullable-type-assertion-style": "warn",
      "react/no-unescaped-entities": "warn",
      "@typescript-eslint/no-empty-object-type": "warn",
      "@typescript-eslint/prefer-nullish-coalescing": "warn",
      "@typescript-eslint/no-inferrable-types": "warn",
      "@typescript-eslint/consistent-indexed-object-style": "warn",
      "@typescript-eslint/prefer-optional-chain": "warn",
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "no-var": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/prefer-includes": "warn",
      "@typescript-eslint/ban-ts-comment": "warn",
      "@typescript-eslint/no-unnecessary-type-assertion": "warn",
      "@typescript-eslint/restrict-template-expressions": "warn",

      // Downgrade a handful of strict rules to warnings so `npm run lint` is informative
      // without blocking the workflow on pre-existing issues across the repo.
      "@typescript-eslint/await-thenable": "warn",
      "@typescript-eslint/no-base-to-string": "warn",
      "@typescript-eslint/no-empty-function": "warn",
      "@typescript-eslint/no-redundant-type-constituents": "warn",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/prefer-find": "warn",
      "@typescript-eslint/prefer-regexp-exec": "warn",
      "@typescript-eslint/unbound-method": "warn",
      "prefer-const": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/rules-of-hooks": "warn",
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/use-memo": "warn",
    },
  },
];
